# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZynqSystem/ZynqSystem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem || ORIG_REF_NAME==ZynqSystem} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_processing_system7_0_0/ZynqSystem_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_processing_system7_0_0 || ORIG_REF_NAME==ZynqSystem_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_axi_gpio_0_0/ZynqSystem_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_axi_gpio_0_0 || ORIG_REF_NAME==ZynqSystem_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_axi_gpio_1_0/ZynqSystem_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_axi_gpio_1_0 || ORIG_REF_NAME==ZynqSystem_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_xbar_0/ZynqSystem_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_xbar_0 || ORIG_REF_NAME==ZynqSystem_xbar_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_auto_pc_0/ZynqSystem_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_auto_pc_0 || ORIG_REF_NAME==ZynqSystem_auto_pc_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_ps7_0_axi_periph_0/ZynqSystem_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZynqSystem_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZynqSystem/ip/ZynqSystem_rst_ps7_0_100M_0/ZynqSystem_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZynqSystem_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZynqSystem_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: d:/Projects/SOC_Projects/Counter_LedSwitch_Zedboard/Counter_LedSwitch_Zedboard.gen/sources_1/bd/ZynqSystem/ZynqSystem_ooc.xdc
